import { arrayBufferToBase64, requestUrl } from 'obsidian';

export interface WeMpAccount {
  id: string;
  name: string;
  avatar?: string;
  description?: string;
  fakeid?: string;
  feedUrl: string;
  subscribed?: boolean;
}

interface ApiResponse<T> {
  code?: number;
  data?: T;
  message?: string;
}

interface MpListResult {
  list?: Array<{
    id: string;
    mp_name?: string;
    mp_cover?: string;
    mp_intro?: string;
  }>;
}

interface SearchResult {
  list?: Array<{
    fakeid?: string;
    id?: string;
    nickname?: string;
    name?: string;
    round_head_img?: string;
    avatar?: string;
    signature?: string;
    description?: string;
  }>;
}

export class WeMpClient {
  private cachedToken: string = '';

  constructor(private getServerUrl: () => string, private getToken: () => string) {}

  public get baseUrl(): string {
    let url = this.getServerUrl().trim();
    if (url.endsWith('/')) url = url.slice(0, -1);
    return url;
  }

  private async ensureToken(): Promise<string> {
    const configured = this.getToken().trim();
    if (configured) return configured;
    if (this.cachedToken) return this.cachedToken;

    // Try login with default admin credentials
    try {
      const loginUrl = `${this.baseUrl}/api/v1/wx/auth/login`;
      const res = await requestUrl({
        url: loginUrl,
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: 'username=admin&password=admin@123',
        throw: false,
      });
      if (res.status === 200) {
        const json = res.json as ApiResponse<{ access_token?: string }>;
        if (json?.data?.access_token) {
          this.cachedToken = json.data.access_token;
          return this.cachedToken;
        }
      }
    } catch (e) {
      console.warn('[WeMpClient] auto login failed:', e);
    }
    return '';
  }

  private async getHeaders(): Promise<Record<string, string>> {
    const token = await this.ensureToken();
    const headers: Record<string, string> = {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
    };
    if (token) {
      headers['Authorization'] = `Bearer ${token}`;
    }
    return headers;
  }

  async checkHealth(): Promise<{ ok: boolean; message: string; requiresAuth?: boolean }> {
    try {
      const rootRes = await requestUrl({ url: `${this.baseUrl}/`, method: 'GET', throw: false });
      if (rootRes.status === 200) {
        const headers = await this.getHeaders();
        const mpsRes = await requestUrl({ url: `${this.baseUrl}/api/v1/wx/mps?limit=1`, method: 'GET', headers, throw: false });
        if (mpsRes.status === 401 || mpsRes.status === 403) {
          return { ok: true, message: '服务在线（需在设置中配置 Access Token）', requiresAuth: true };
        }
        return { ok: true, message: '服务在线且连接正常' };
      }
      return { ok: false, message: `服务响应异常 (HTTP ${rootRes.status})` };
    } catch (e) {
      return { ok: false, message: `无法连接服务器: ${e instanceof Error ? e.message : String(e)}` };
    }
  }

  async getQrCode(onProgress?: (msg: string) => void): Promise<{ ok: boolean; qrImageUrl: string; message: string }> {
    try {
      const headers = await this.getHeaders();
      const url = `${this.baseUrl}/api/v1/wx/auth/qr/code`;
      const res = await requestUrl({ url, method: 'GET', headers, throw: false });
      if (res.status !== 200) {
        return { ok: false, qrImageUrl: '', message: `请求二维码接口失败 (HTTP ${res.status})` };
      }

      onProgress?.('云端正在生成最新微信登录二维码…');

      // Poll until qr_code is generated by headless browser (timeout after 30 seconds)
      const startTime = Date.now();
      let isReady = false;
      while (Date.now() - startTime < 30000) {
        const status = await this.checkQrStatus();
        if (status.qrCode) {
          isReady = true;
          break;
        }
        await new Promise(resolve => window.setTimeout(resolve, 1500));
      }

      if (!isReady) {
        return { ok: false, qrImageUrl: '', message: '云端生成二维码超时，请点击重试' };
      }

      onProgress?.('正在下载二维码图片…');
      const imgUrl = `${this.baseUrl}/static/wx_qrcode.png?t=${Date.now()}`;
      const imgRes = await requestUrl({ url: imgUrl, method: 'GET', throw: false });
      if (imgRes.status === 200 && imgRes.arrayBuffer) {
        const base64 = arrayBufferToBase64(imgRes.arrayBuffer);
        return {
          ok: true,
          qrImageUrl: `data:image/png;base64,${base64}`,
          message: '获取成功',
        };
      }

      return { ok: false, qrImageUrl: '', message: `下载二维码图片失败 (HTTP ${imgRes.status})` };
    } catch (e) {
      return { ok: false, qrImageUrl: '', message: e instanceof Error ? e.message : String(e) };
    }
  }

  async checkQrStatus(): Promise<{ loginStatus: boolean; qrCode: boolean }> {
    try {
      const headers = await this.getHeaders();
      const url = `${this.baseUrl}/api/v1/wx/auth/qr/status`;
      const res = await requestUrl({ url, method: 'GET', headers, throw: false });
      if (res.status === 200) {
        const json = res.json as ApiResponse<{ login_status?: boolean; qr_code?: boolean }>;
        return {
          loginStatus: Boolean(json?.data?.login_status),
          qrCode: Boolean(json?.data?.qr_code),
        };
      }
      return { loginStatus: false, qrCode: false };
    } catch {
      return { loginStatus: false, qrCode: false };
    }
  }

  async listSubscribedMps(): Promise<WeMpAccount[]> {
    try {
      const headers = await this.getHeaders();
      const url = `${this.baseUrl}/api/v1/wx/mps?limit=100`;
      const res = await requestUrl({ url, method: 'GET', headers, throw: false });
      if (res.status === 200) {
        const json = res.json as ApiResponse<MpListResult> | undefined;
        const list = json?.data?.list ?? [];
        return list.map(item => ({
          id: String(item.id),
          name: item.mp_name ?? '未命名公众号',
          avatar: item.mp_cover?.startsWith('http') ? item.mp_cover : `${this.baseUrl}${item.mp_cover ?? ''}`,
          description: item.mp_intro ?? '',
          feedUrl: `${this.baseUrl}/feed/${item.id}.xml`,
          subscribed: true,
        }));
      }
      return [];
    } catch (e) {
      console.error('[WeMpClient] listSubscribedMps error:', e);
      return [];
    }
  }

  async searchAccounts(keyword: string): Promise<WeMpAccount[]> {
    if (!keyword.trim()) return [];
    try {
      const headers = await this.getHeaders();
      const query = encodeURIComponent(keyword.trim());
      const url = `${this.baseUrl}/api/v1/wx/mps/search/${query}`;
      const res = await requestUrl({ url, method: 'GET', headers, throw: false });
      if (res.status === 200) {
        const json = res.json as ApiResponse<SearchResult> | undefined;
        const list = json?.data?.list ?? [];
        return list.map(item => ({
          id: String(item.fakeid ?? item.id ?? ''),
          name: item.nickname ?? item.name ?? keyword,
          avatar: item.round_head_img ?? item.avatar ?? '',
          description: item.signature ?? item.description ?? '',
          fakeid: item.fakeid ?? '',
          feedUrl: `${this.baseUrl}/feed/${item.id ?? item.fakeid ?? ''}.xml`,
          subscribed: false,
        }));
      }
      return [];
    } catch (e) {
      console.error('[WeMpClient] searchAccounts error:', e);
      return [];
    }
  }

  async subscribe(account: WeMpAccount): Promise<{ ok: boolean; feedUrl: string; message: string }> {
    try {
      const headers = await this.getHeaders();
      const url = `${this.baseUrl}/api/v1/wx/mps`;
      const res = await requestUrl({
        url,
        method: 'POST',
        headers,
        body: JSON.stringify({
          mp_name: account.name,
          mp_id: account.fakeid ?? account.id,
          avatar: account.avatar ?? '',
          mp_intro: account.description ?? '',
        }),
        throw: false,
      });

      if (res.status >= 200 && res.status < 300) {
        const json = res.json as ApiResponse<{ id?: string }> | undefined;
        const feedId = json?.data?.id ?? account.id;
        return { ok: true, feedUrl: `${this.baseUrl}/feed/${feedId}.xml`, message: '订阅成功' };
      }
      return { ok: true, feedUrl: `${this.baseUrl}/feed/${account.id}.xml`, message: '已提交订阅' };
    } catch {
      return { ok: true, feedUrl: `${this.baseUrl}/feed/${account.id}.xml`, message: '添加订阅源' };
    }
  }

  async updateMpArticles(mpId: string): Promise<{ ok: boolean; message: string }> {

    try {
      const headers = await this.getHeaders();
      const url = `${this.baseUrl}/api/v1/wx/mps/update/${mpId}`;
      const res = await requestUrl({ url, method: 'GET', headers, throw: false });
      if (res.status === 200) {
        return { ok: true, message: '已触发云端同步抓取，请稍候刷新查看' };
      }
      return { ok: false, message: `触发同步失败 (HTTP ${res.status})` };
    } catch (e) {
      return { ok: false, message: e instanceof Error ? e.message : String(e) };
    }
  }

  async importArticle(articleUrl: string): Promise<{ ok: boolean; message: string; feedUrl: string; title?: string }> {
    try {
      const headers = await this.getHeaders();
      const url = `${this.baseUrl}/api/v1/wx/mps/featured/article`;
      const res = await requestUrl({
        url,
        method: 'POST',
        headers,
        body: JSON.stringify({ url: articleUrl.trim() }),
        throw: false,
      });
      if (res.status < 200 || res.status >= 300) {
        return { ok: false, message: `提交抓取任务失败 (HTTP ${res.status})`, feedUrl: '' };
      }
      const json = res.json as ApiResponse<{ task_id?: string }>;
      const taskId = json?.data?.task_id;
      const feedUrl = `${this.baseUrl}/feed/MP_WXS_FEATURED_ARTICLES.xml`;
      if (!taskId) {
        return { ok: true, message: '文章已加入抓取队列', feedUrl };
      }

      // Poll task status until complete or timeout (up to 30s)
      const start = Date.now();
      while (Date.now() - start < 30000) {
        await new Promise((r) => window.setTimeout(r, 1500));
        try {
          const pollRes = await requestUrl({
            url: `${this.baseUrl}/api/v1/wx/mps/featured/article/tasks/${taskId}`,
            method: 'GET',
            headers,
            throw: false,
          });
          if (pollRes.status === 200) {
            const taskData = (pollRes.json as ApiResponse<{ status?: string; message?: string; title?: string }>)?.data;
            if (taskData?.status === 'success') {
              return {
                ok: true,
                message: '文章抓取成功',
                feedUrl,
                title: taskData.title,
              };
            }
            if (taskData?.status === 'failed') {
              return {
                ok: false,
                message: taskData.message || '文章抓取失败',
                feedUrl,
              };
            }
          }
        } catch {
          // ignore transient poll error
        }
      }

      return {
        ok: true,
        message: '任务在后台执行中，请稍后刷新查看',
        feedUrl,
      };
    } catch (e) {
      return { ok: false, message: e instanceof Error ? e.message : String(e), feedUrl: '' };
    }
  }
}

